apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: playground
    tier: gateway
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: playground
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: playground
      tier: gateway
  replicas: 4
  template:
    metadata:
      labels:
        app: playground
        tier: gateway
    spec:
      containers:
        - name: default
          image: docker.io/carabas/k8s-playground
          env:
            - name: PLAYGROUND_PORT
              value: "8000"
          ports:
            - containerPort: 8000
