apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: playground
    tier: gateway
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: playground
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: playground
      tier: gateway
  replicas: 4
  template:
    metadata:
      labels:
        app: playground
        tier: gateway
    spec:
      containers:
        - name: default
          image: docker.io/carabas/k8s-playground@sha256:380096e23406d93bde4629b2a595bee7fd2a78a5c987bbb2f5adbd5ddb31ad6c
          resources:
            requests:
              cpu: 500m
          env:
            - name: PLAYGROUND_PORT
              value: "8000"
          ports:
            - containerPort: 8000
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gateway
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50
---
# Grant kubernetes-dashboard user full admin access
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-dashboard
  labels:
    k8s-app: kubernetes-dashboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kubernetes-dashboard
    namespace: kube-system
